name 'sonarqube'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
license 'MIT'
description 'Installs/Configures sonarqube'
long_description 'Installs/Configures sonarqube'
version '0.1.0'
supports 'ubuntu'
supports 'centos'
