name 'sonarqube'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
license 'MIT'
description 'Installs/Configures SonarQube'
long_description 'Installs/Configures SonarQube'
version '0.3.0'
supports 'ubuntu'
supports 'centos'
